/** @format */

import Head from 'next/head';
import Calculator from './components/calculator';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Simple Calculator</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Calculator />
      </main>

      <footer className={styles.footer} />
    </div>
  );
}
